version: '2'

services:

    my-app-db:
        image: mysql:5.5.57
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'Admin123'
            MYSQL_DATABASE: 'my_app_db'
            MYSQL_USER: 'my_user'
            MYSQL_PASSWORD: 'User123'
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./ci/docker/.data/dbtest:/var/lib/mysql
